- name: Backup configuracion inicial
  gather_facts: false
  hosts: juniper
  tasks:
    - name: Guardar Archivo
      junipernetworks.junos.junos_config:
        backup: yes
        backup_options:
          dir_path: /root/respaldos/juniper/
          backup_format: json
          filename: 
