- name: Backup Cisco
  hosts: gns3-ios
  connection: network_cli
  gather_facts: false
  tasks:
    - name: Prueba de acceso
      ios_facts:
        gather_subset: all
    - name: Obtener fecha actual
      local_action: command date +%Y-%b-%d
      register: date
    - name: Obtener hora local
      local_action: command date +%H:%M
      register: time
    - name: Realizar Back up
      ios_config:
       backup: yes
       backup_options:
         filename: "{{ ansible_net_hostname }}_{{ ansible_host }}.cfg"
         dir_path: /root/respaldos/cisco/{{ date.stdout }}_at_{{ time.stdout }}
    - name: Tasks done
      debug: msg="Todas las tareas se han realizado correctamente el dia {{ date.stdout }} a las {{ time.stdout }}."
