- name:Crear Vlan
  cisco.ios.ios_interfaces
    config
    - name= "{{ VLAN }}"
      description= "{{ DESCRIPCION }}"
    - name= Configurar Vlan 
      cisco.ios.ios_config:
        lines=
        - interface "{{ PARENTESCO}}"
        - description "{{ DESCRIPCION }}"
        - name "{{ DESCRIPCION }}"
        parents: interface "{{ PARENTESCO }}"
      with_items=
      - interface {{ PARENTESCO }}

